substitutions:
  _REPOSITORY: 'us-central1-docker.pkg.dev/buoyant-notch-437915-p4/images'
  _IMAGE: '${_REPOSITORY}/hw_python'
  _VERSION: 'snapshot_1.3'

steps:
  - name: 'bash'
    script: 'echo valor do COMMIT_SHA: $COMMIT_SHA'
  # Passo 1: Validar se a tag já existe no repositório remoto
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TAG_EXISTS=$(git ls-remote --tags origin refs/tags/${_VERSION_TAG})
        if [ -n "$$TAG_EXISTS" ]; then
          echo "Tag ${_VERSION_TAG} já existe. Interrompendo o build."
          exit 0  # Não falha, mas interrompe o build
        else
          echo "Tag ${_VERSION_TAG} não existe. Continuando..."
        fi

  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', '${_IMAGE}:${_VERSION}', '.']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', '${_IMAGE}:${_VERSION}']

options:
  logging: CLOUD_LOGGING_ONLY