substitutions:
  _REPOSITORY: 'us-central1-docker.pkg.dev/buoyant-notch-437915-p4/images'
  _IMAGE: '${_REPOSITORY}/hw_python'
  _VERSION: 'snapshot_1.5'
  _GITHUB: 'https://github.com/$REPO_FULL_NAME'

availableSecrets:
  secretManager:
  - versionName: projects/592977005222/secrets/passgithub/versions/latest
    env: 'SSH_KEY'

# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
    git clone git@github.com:$REPO_FULL_NAME
    git checkout $COMMIT_SHA
    git tag ${_VERSION}
    git push origin --tags
  volumes:
  - name: 'ssh'
    path: /root/.ssh




  # 3. Constrói a imagem com a versão calculada e realiza o push
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', '${_IMAGE}:${_VERSION}', '.']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', '${_IMAGE}:${_VERSION}']

options:
  logging: CLOUD_LOGGING_ONLY