substitutions:
  _REPOSITORY: 'us-central1-docker.pkg.dev/buoyant-notch-437915-p4/images'
  _IMAGE: '${_REPOSITORY}/hw_python'
  _TAG: 'v0.4'

steps:
- name: 'us-central1-docker.pkg.dev/buoyant-notch-437915-p4/devops/gitwithgh:v0.5'
  entrypoint: 'bash'
  args:
  - -xc
  - |
    git clone git@github.com:/$REPO_FULL_NAME.git repo
    cd repo
    git checkout $COMMIT_SHA
    if [ "$BRANCH_NAME" == "main" ]; then
      TAG_NAME="${_TAG}"
      gh auth login --with-token < /root/token
      gh release create $$TAG_NAME --title "Release $$TAG_NAME" --notes "Docker image published on ${_IMAGE}:$$TAG_NAME"
    else
      TAG_NAME="snapshot-$(date +%Y%m%d%H%M%S)"
      git tag $$TAG_NAME
      git push origin $$TAG_NAME
    fi
    echo "$$TAG_NAME" >> /root/tag/tag
  volumes:
    - name: 'tag'
      path: /root/tag
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: "bash"
  args:
  - -xc
  - |
    export tag=$(cat /root/tag/tag)
    docker build -t ${_IMAGE}:$$tag .
    docker push ${_IMAGE}:$$tag
  volumes:
    - name: 'tag'
      path: /root/tag

options:
  logging: CLOUD_LOGGING_ONLY