substitutions:
  _REPOSITORY: 'us-central1-docker.pkg.dev/buoyant-notch-437915-p4/images'
  _IMAGE: '${_REPOSITORY}/hw_python'
  _VERSION: 'snapshot_1.6'

availableSecrets:
  secretManager:
  - versionName: projects/592977005222/secrets/passgithub/versions/latest
    env: 'SSH_KEY'

# Access the id_rsa file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - git@github.com:$REPO_FULL_NAME.git
  - repo
  volumes:
  - name: 'ssh'
    path: '/root/.ssh'

- name: 'gcr.io/cloud-builders/git'
  dir: 'repo'
  args:
  - checkout
  - $COMMIT_SHA

- name: 'gcr.io/cloud-builders/git'
  dir: repo
  args:
  - tag ${_VERSION}

- name: 'gcr.io/cloud-builders/git'
  dir: repo
  args:
  - git push origin ${_VERSION}
  volumes:
  - name: 'ssh'
    path: /root/.ssh



  # 3. Constrói a imagem com a versão calculada e realiza o push
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', '${_IMAGE}:${_VERSION}', '.']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', '${_IMAGE}:${_VERSION}']

options:
  logging: CLOUD_LOGGING_ONLY