substitutions:
  _REPOSITORY: 'us-central1-docker.pkg.dev/buoyant-notch-437915-p4/images'
  _IMAGE: '${_REPOSITORY}/hw_python'
  _VERSION: 'snapshot_1.3'

steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo valor do COMMIT_SHA: $COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo valor do SHORT_SHA: $SHORT_SHA'
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo valor do REPO_FULL_NAME: $REPO_FULL_NAME'
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo valor do BRANCH_NAME: $BRANCH_NAME'


  # - name: 'bash'
  #   script: |
  #     echo valor do PROJECT_ID: $PROJECT_ID
  #     echo valor do BUILD_ID: $BUILD_ID
  #     echo valor do PROJECT_NUMBER: $PROJECT_NUMBER
  #     echo valor do LOCATION: $LOCATION
  #     echo valor do TRIGGER_NAME: $TRIGGER_NAME
  #     echo valor do COMMIT_SHA: $COMMIT_SHA
  #     echo valor do REVISION_ID: $REVISION_ID
  #     echo valor do SHORT_SHA: $SHORT_SHA
  #     echo valor do REPO_NAME: $REPO_NAME
  #     echo valor do REPO_FULL_NAME: $REPO_FULL_NAME
  #     echo valor do BRANCH_NAME: $BRANCH_NAME
  #     echo valor do TAG_NAME: $TAG_NAME
  #     echo valor do REF_NAME: $REF_NAME
  #     echo valor do TRIGGER_BUILD_CONFIG_PATH: $TRIGGER_BUILD_CONFIG_PATH
  #     echo valor do SERVICE_ACCOUNT_EMAIL: $SERVICE_ACCOUNT_EMAIL
  #     echo valor do SERVICE_ACCOUNT: $SERVICE_ACCOUNT
  #     echo valor do _HEAD_BRANCH: $_HEAD_BRANCH
  #     echo valor do _BASE_BRANCH: $_BASE_BRANCH
  #     echo valor do _HEAD_REPO_URL: $_HEAD_REPO_URL
  #     echo valor do _PR_NUMBER: $_PR_NUMBER
  #     echo valor do TRIGGER_NAME: $TRIGGER_NAME
  #     echo valor do COMMIT_SHA: $COMMIT_SHA
  #     echo valor do REVISION_ID: $REVISION_ID
  #     echo valor do SHORT_SHA: $SHORT_SHA
  #     echo valor do REPO_NAME: $REPO_NAME
  #     echo valor do REPO_FULL_NAME: $REPO_FULL_NAME
  #     echo valor do BRANCH_NAME: $BRANCH_NAME
  #     echo valor do TAG_NAME: $TAG_NAME
  #     echo valor do REF_NAME: $REF_NAME
  #     echo valor do TRIGGER_BUILD_CONFIG_PATH: $TRIGGER_BUILD_CONFIG_PATH
  #     echo valor do SERVICE_ACCOUNT_EMAIL: $SERVICE_ACCOUNT_EMAIL
  #     echo valor do SERVICE_ACCOUNT: $SERVICE_ACCOUNT




  # Passo 1: Validar se a tag já existe no repositório remoto
  # - name: 'gcr.io/cloud-builders/git'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       TAG_EXISTS=$(git ls-remote --tags origin refs/tags/${_VERSION_TAG})
  #       if [ -n "$$TAG_EXISTS" ]; then
  #         echo "Tag ${_VERSION_TAG} já existe. Interrompendo o build."
  #         exit 0  # Não falha, mas interrompe o build
  #       else
  #         echo "Tag ${_VERSION_TAG} não existe. Continuando..."
  #       fi

  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', '${_IMAGE}:${_VERSION}', '.']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', '${_IMAGE}:${_VERSION}']

options:
  logging: CLOUD_LOGGING_ONLY