steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'images/python-hello-world:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'images/python-hello-world:latest']

images:
  - 'images/python-hello-world:latest'

options:
  logging: CLOUD_LOGGING_ONLY