substitutions:
  _repository: 'us-central1-docker.pkg.dev/buoyant-notch-437915-p4/images'
  _image: '${_repository}/hw_python'
  _version: 'snapshot_1.0'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_image}:${_version}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_image}:${_version}', '.']

options:
  logging: CLOUD_LOGGING_ONLY