substitutions:
  _REPOSITORY: 'us-central1-docker.pkg.dev/buoyant-notch-437915-p4/images'
  _IMAGE: '${_REPOSITORY}/hw_python'
  _PREFIX: 'v1'

steps:
- name: 'us-central1-docker.pkg.dev/buoyant-notch-437915-p4/devops/gitwithgh:v0.5'
  entrypoint: 'bash'
  args:
  - -xc
  - |
    git clone git@github.com:/$REPO_FULL_NAME.git repo
    cd repo
    git checkout $COMMIT_SHA
    if [ "$BRANCH_NAME" == "main" ]; then
      LAST_TAG=$(git tag | grep "^${_PREFIX}" | sort -V | tail -n 1)
      if [[ -z "$$LAST_TAG" ]]; then
        NEW_TAG="${_PREFIX}.0"
      else
        # Incrementa a última subversão (ex: v1.5 -> v1.6)
        NEW_TAG="$${LAST_TAG%.*}.$$(($${LAST_TAG##*.} + 1))"
      fi
      gh auth login --with-token < /root/token
      gh release create $$NEW_TAG --title "Release $$NEW_TAG" --notes "Docker image published on ${_IMAGE}:$$NEW_TAG"
    else
      NEW_TAG="snapshot-$(date +%Y%m%d%H%M%S)"
      git tag $$NEW_TAG
      git push origin $$NEW_TAG
    fi
    echo "$$NEW_TAG" >> /root/tag/tag
  volumes:
    - name: 'tag'
      path: /root/tag
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: "bash"
  args:
  - -xc
  - |
    export tag=$(cat /root/tag/tag)
    docker build -t ${_IMAGE}:$$tag .
    docker push ${_IMAGE}:$$tag
  volumes:
    - name: 'tag'
      path: /root/tag

options:
  logging: CLOUD_LOGGING_ONLY